### PR TITLE
Add server updater script

### PR DESCRIPTION
**Pull request by t3slider**
Dependencies: bash, xmllint, curl, coreutils

### CODE REVIEW

**Comment by Barbatos** [comment]
Many thanks for this awesome contribution. I'll test it soon and merge it asap!

**Comment by t3slider** [comment]
I noticed two things I missed from the client updater. The chmod of Linux binaries (see faab5fb, same branch [master]) and the unzipping of zip files (see 4870430, zip branch). The old server updater didn't unzip files and as far as I know the only zip file now is the Mac launcher, and unzipping adds a new dependency (unzip from InfoZip). I'm not sure if that functionality is needed or not but you can merge it after if it is (or ask me to submit another pull request when/if this one closes).

**Comment by Barbatos** [comment]
Yeah unzipping is only required for Mac builds so we don't need it for the server Updater!

**Comment by Barbatos** [comment]
Hey sorry for the laaaate answer (as usual). I tested your Updater for dedicated servers and I found only one issue: for an unknown reason it looks like the Updater isn't downloading the engine files. 

I'll investigate further and FYI I updated the mirrors and API so you can test the Updater as well with the latest version (4.2.023).

**Comment by t3slider** [comment]
The issue is that the server doesn't respond with the engine files to download when issuing a versionFiles request. I haven't built the client updater recently so I haven't tested what is happening there, but I'm not sure if this is an issue with the upstream API or with the server updater passing incorrect parameters to the API's versionFiles request which then omits the engine files in the response.

When I initially played around with the API (when the only version available was 4.2.018, I think) it produced some invalid XML (can't remember if it was in the versionInfo or versionFiles response) but there were two Files sections, one with the pk3s and one with the engine files. When the API was updated (along with the 4.2.021 bump I think), the XML it produced was valid (good), but the second Files section was empty, as it is now (it is just `<Files/>`).

The current updater script was written with the second Files section in mind, so I believe it should work when that section is present. However, as I said above, I don't know if the request or the API is responsible for that section being empty, so I don't know where to start looking.

**Comment by Barbatos** [comment]
Yep you were right, it was an issue on the API side. It's fixed and working fine now!

The Updater in its current form looks really good to me. Something that will be requested by server admins though will be to have a -q (--quiet) flag so they can run the Updater in a crontab. What do you think about it?

**Comment by t3slider** [comment]
Added a -q option. The first run must be interactive to accept the license and choose settings but subsequent runs can be non-interactive. There will only be output if an error is encountered (so cron logs should be empty unless something goes wrong, which should be expected behaviour), and it should never wait for input.

**Comment by Barbatos** [comment]
You Sir are awesome! Many thanks for your contribution.

**Pull request merged**
